# Generated by Django 5.0.4 on 2024-04-29 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_comment_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('headline', models.CharField(max_length=255)),
                ('text1', models.TextField()),
                ('picture1', models.ImageField(blank=True, null=True, upload_to='article_pictures/')),
                ('pic_description1', models.CharField(blank=True, max_length=255, null=True)),
                ('text2', models.TextField(blank=True, null=True)),
                ('picture2', models.ImageField(blank=True, null=True, upload_to='article_pictures/')),
                ('pic_description2', models.CharField(blank=True, max_length=255, null=True)),
                ('text3', models.TextField(blank=True, null=True)),
                ('picture3', models.ImageField(blank=True, null=True, upload_to='article_pictures/')),
                ('pic_description3', models.CharField(blank=True, max_length=255, null=True)),
                ('text4', models.TextField(blank=True, null=True)),
                ('visibility', models.BooleanField(default=False)),
                ('position', models.IntegerField(choices=[(0, 'Position 0'), (1, 'Position 1'), (2, 'Position 2'), (3, 'Position 3')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
