# Generated by Django 5.0.4 on 2024-04-29 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_comment_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='article_id',
        ),
    ]
