# Generated by Django 5.0.4 on 2024-04-29 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_rename_article_comment_article_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author',
            new_name='author_id',
        ),
    ]
