# Generated by Django 5.0.4 on 2024-04-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_alter_comment_article_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='position',
            field=models.IntegerField(choices=[(0, 'Position 0'), (1, 'Position 1')], default=0),
        ),
    ]
